// src/app/projects/projects.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-projects',
  templateUrl: './projects.component.html',
  standalone: true
})
export class ProjectsComponent {

}


<div class="experience-container">
    <div class="greeting text-blue">Our Work</div>
    <p class="fs-3 fw-bold my-3">Featured projects</p>
    <p class="text-secondary mb-3">Explore our portfolio of recent projects showcasing our expertise in web development, mobile applications, and interactive experiences.</p>
    <div class="mt-4">
        <div class="row">
            <div class="col-lg-4 col-md-6 col-sm-12 mb-5">
                <div class="indigo-midnight-border rounded-3 overflow-hidden">
                    <div class="h-200 w-100 indigo-midnight-grad"></div>
                    <div class="p-4">
                        <div class="greeting text-blue mb-3">Web Application</div>
                        <p class="text-large fw-bold mb-3">Disteven</p>
                        <p class="text-secondary mb-3">Disteven is your all-in-one solution for effortlessly managing groups, friends, expenses, and their resolutions.</p>
                        <div class="d-flex align-items-center gap-3 mb-5 flex-wrap">
                            <div class="badge-gray">HTML</div>
                            <div class="badge-gray">SCSS</div>
                            <div class="badge-gray">Bootstrap</div>
                            <div class="badge-gray">Angular</div>
                            <div class="badge-gray">Node.js</div>
                            <div class="badge-gray">MongoDB</div>
                            <div class="badge-gray">Express</div>
                        </div>
                        <a href="https://app.disteven.com" target="_blank" class="text-decoration-none">
                            View project
                            <i class="bi bi-arrow-right"></i>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 mb-5">
                <div class="purple-magenta-border rounded-3 overflow-hidden">
                    <div class="h-200 w-100 purple-magenta-grad"></div>
                    <div class="p-4">
                        <div class="greeting text-blue mb-3">Web Application</div>
                        <p class="text-large fw-bold mb-3">Cipher Bay</p>
                        <p class="text-secondary mb-3"> A secure platform for encrypting and decrypting text online.</p>
                        <div class="d-flex align-items-center gap-3 mb-5 flex-wrap">
                            <div class="badge-gray">HTML</div>
                            <div class="badge-gray">SCSS</div>
                            <div class="badge-gray">Angular</div>
                            <div class="badge-gray">Node.js</div>
                            <div class="badge-gray">MongoDB</div>
                            <div class="badge-gray">Express</div>
                        </div>
                        <a href="https://cipherbay.vercel.app/home" target="_blank" class="text-decoration-none">
                            View project
                            <i class="bi bi-arrow-right"></i>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 mb-5">
                <div class="gray-emerald-border rounded-3 overflow-hidden">
                    <div class="h-200 w-100 gray-emerald-grad"></div>
                    <div class="p-4">
                        <div class="greeting text-blue mb-3">Web Application</div>
                        <p class="text-large fw-bold mb-3">Collatz Conjecture</p>
                        <p class="text-secondary mb-3">A visualization of the Collatz Conjecture to explore mathematical patterns.</p>
                        <div class="d-flex align-items-center gap-3 mb-5 flex-wrap">
                            <div class="badge-gray">HTML</div>
                            <div class="badge-gray">CSS</div>
                            <div class="badge-gray">JavaScript</div>
                            <div class="badge-gray">Node.js</div>
                        </div>
                        <a href="https://collatz-visual.netlify.app/" target="_blank" class="text-decoration-none">
                            View project
                            <i class="bi bi-arrow-right"></i>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 mb-5">
                <div class="green-cyan-border rounded-3 overflow-hidden">
                    <div class="h-200 w-100 green-cyan-grad"></div>
                    <div class="p-4">
                        <div class="greeting text-blue mb-3">Web Application</div>
                        <p class="text-large fw-bold mb-3">Colors Expo</p>
                        <p class="text-secondary mb-3">A color palette exploration tool for designers and developers.</p>
                        <div class="d-flex align-items-center gap-3 mb-5 flex-wrap">
                            <div class="badge-gray">HTML</div>
                            <div class="badge-gray">CSS</div>
                            <div class="badge-gray">JavaScript</div>
                        </div>
                        <a href="https://find-colors.netlify.app/" target="_blank" class="text-decoration-none">
                            View project
                            <i class="bi bi-arrow-right"></i>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 mb-5">
                <div class="blue-violet-border rounded-3 overflow-hidden">
                    <div class="h-200 w-100 blue-violet-grad"></div>
                    <div class="p-4">
                        <div class="greeting text-blue mb-3">Web Application</div>
                        <p class="text-large fw-bold mb-3">Lottery Matching app</p>
                        <p class="text-secondary mb-3">A random lottery number matcher for testing luck.</p>
                        <div class="d-flex align-items-center gap-3 mb-5 flex-wrap">
                            <div class="badge-gray">HTML</div>
                            <div class="badge-gray">CSS</div>
                            <div class="badge-gray">JavaScript</div>
                        </div>
                        <a href="https://lottery-js.netlify.app/" target="_blank" class="text-decoration-none">
                            View project
                            <i class="bi bi-arrow-right"></i>
                        </a>
                    </div>  
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 mb-5">
                <div class="indigo-midnight-border rounded-3 overflow-hidden">
                    <div class="h-200 w-100 indigo-midnight-grad"></div>
                    <div class="p-4">
                        <div class="greeting text-blue mb-3">Web Application</div>
                        <p class="text-large fw-bold mb-3">Pop It</p>
                        <p class="text-secondary mb-3">A casual popping game for quick, addictive and relaxing gameplay.</p>
                        <div class="d-flex align-items-center gap-3 mb-5 flex-wrap">
                            <div class="badge-gray">HTML</div>
                            <div class="badge-gray">CSS</div>
                            <div class="badge-gray">JavaScript</div>
                        </div>
                        <a href="https://pop-game.netlify.app/" target="_blank" class="text-decoration-none">
                            View project
                            <i class="bi bi-arrow-right"></i>
                        </a>
                    </div>  
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 mb-5">
                <div class="purple-magenta-border rounded-3 overflow-hidden">
                    <div class="h-200 w-100 purple-magenta-grad"></div>
                    <div class="p-4">
                        <div class="greeting text-blue mb-3">Web Application</div>
                        <p class="text-large fw-bold mb-3">Quiz It</p>
                        <p class="text-secondary mb-3">A fun and engaging quiz application for testing knowledge.</p>
                        <div class="d-flex align-items-center gap-3 mb-5 flex-wrap">
                            <div class="badge-gray">HTML</div>
                            <div class="badge-gray">CSS</div>
                            <div class="badge-gray">JavaScript</div>
                        </div>
                        <a href="https://quiz-jam.netlify.app/index.html" target="_blank" class="text-decoration-none">
                            View project
                            <i class="bi bi-arrow-right"></i>
                        </a>
                    </div>  
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 mb-5">
                <div class="gray-emerald-border rounded-3 overflow-hidden">
                    <div class="h-200 w-100 gray-emerald-grad"></div>
                    <div class="p-4">
                        <div class="greeting text-blue mb-3">Web Application</div>
                        <p class="text-large fw-bold mb-3">les papilles</p>
                        <p class="text-secondary mb-3">A visually appealing food, restaurant and online ordering website.</p>
                        <div class="d-flex align-items-center gap-3 mb-5 flex-wrap">
                            <div class="badge-gray">HTML</div>
                            <div class="badge-gray">CSS</div>
                            <div class="badge-gray">JavaScript</div>
                            <div class="badge-gray">Bootstrap</div>
                        </div>
                        <a href="https://les-papilles.netlify.app/#m" target="_blank" class="text-decoration-none">
                            View project
                            <i class="bi bi-arrow-right"></i>
                        </a>
                    </div>  
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 mb-5">
                <div class="green-cyan-border rounded-3 overflow-hidden">
                    <div class="h-200 w-100 green-cyan-grad"></div>
                    <div class="p-4">
                        <div class="greeting text-blue mb-3">Web Application</div>
                        <p class="text-large fw-bold mb-3">Temperature Plot Chart</p>
                        <p class="text-secondary mb-3">An interactive temperature plot chart to visualize yearly trends.</p>
                        <div class="d-flex align-items-center gap-3 mb-5 flex-wrap">
                            <div class="badge-gray">HTML</div>
                            <div class="badge-gray">CSS</div>
                            <div class="badge-gray">JavaScript</div>
                        </div>
                        <a href="https://yearly-temperature.netlify.app/" target="_blank" class="text-decoration-none">
                            View project
                            <i class="bi bi-arrow-right"></i>
                        </a>
                    </div>  
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 mb-5">
                <div class="blue-violet-border rounded-3 overflow-hidden">
                    <div class="h-200 w-100 blue-violet-grad"></div>
                    <div class="p-4">
                        <div class="greeting text-blue mb-3">Web Application</div>
                        <p class="text-large fw-bold mb-3">URL Shortner</p>
                        <p class="text-secondary mb-3">A simple and efficient URL shortener for quick link management.</p>
                        <div class="d-flex align-items-center gap-3 mb-5 flex-wrap">
                            <div class="badge-gray">HTML</div>
                            <div class="badge-gray">CSS</div>
                            <div class="badge-gray">JavaScript</div>
                            <div class="badge-gray">Node.js</div>
                            <div class="badge-gray">MongoDB</div>
                            <div class="badge-gray">Express</div>
                        </div>
                        <a href="https://fexy.vercel.app/" target="_blank" class="text-decoration-none">
                            View project
                            <i class="bi bi-arrow-right"></i>
                        </a>
                    </div>  
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 mb-5">
                <div class="indigo-midnight-border rounded-3 overflow-hidden">
                    <div class="h-200 w-100 indigo-midnight-grad"></div>
                    <div class="p-4">
                        <div class="greeting text-blue mb-3">Web Application</div>
                        <p class="text-large fw-bold mb-3">Error Service</p>
                        <p class="text-secondary mb-3">A random word generator for creative inspiration and brainstorming.</p>
                        <div class="d-flex align-items-center gap-3 mb-5 flex-wrap">
                            <div class="badge-gray">HTML</div>
                            <div class="badge-gray">CSS</div>
                            <div class="badge-gray">JavaScript</div>
                        </div>
                        <a href="https://wrng.netlify.app/" target="_blank" class="text-decoration-none">
                            View project
                            <i class="bi bi-arrow-right"></i>
                        </a>
                    </div>  
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 mb-5">
                <div class="purple-magenta-border rounded-3 overflow-hidden">
                    <div class="h-200 w-100 purple-magenta-grad"></div>
                    <div class="p-4">
                        <div class="greeting text-blue mb-3">Web Application</div>
                        <p class="text-large fw-bold mb-3">To Do List</p>
                        <p class="text-secondary mb-3">A simple and efficient to-do list web app for task management.</p>
                        <div class="d-flex align-items-center gap-3 mb-5 flex-wrap">
                            <div class="badge-gray">HTML</div>
                            <div class="badge-gray">CSS</div>
                            <div class="badge-gray">JavaScript</div>
                        </div>
                        <a href="https://manage-todo.netlify.app/" target="_blank" class="text-decoration-none">
                            View project
                            <i class="bi bi-arrow-right"></i>
                        </a>
                    </div>  
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-12 mb-5">
                <div class="gray-emerald-border rounded-3 overflow-hidden">
                    <div class="h-200 w-100 gray-emerald-grad"></div>
                    <div class="p-4">
                        <div class="greeting text-blue mb-3">Web Application</div>
                        <p class="text-large fw-bold mb-3">Big Oven</p>
                        <p class="text-secondary mb-3">A recipe and meal planning app to explore and manage cooking ideas easily.</p>
                        <div class="d-flex align-items-center gap-3 mb-5 flex-wrap">
                            <div class="badge-gray">HTML</div>
                            <div class="badge-gray">CSS</div>
                            <div class="badge-gray">JavaScript</div>
                        </div>
                        <a href="https://big-oven.netlify.app/" target="_blank" class="text-decoration-none">
                            View project
                            <i class="bi bi-arrow-right"></i>
                        </a>
                    </div>  
                </div>
            </div>
        </div>
    </div>
</div>

// app/projects/page.tsx
import Link from "next/link"
import Image from "next/image"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { ArrowRight } from "lucide-react"
import { PageTransition } from '@/components/page-transition'
import AnimatedGradientText from "@/components/animated-gradient-text"

// Sample project data
const projects = [
  {
    id: 1,
    title: "Disteven",
    client: "",
    category: "Web Development, UI/UX Design",
    description:
      "Disteven is your all-in-one solution for effortlessly managing groups, friends, expenses, and their resolutions.",
    image: "/disteven.PNG",
    demoUrl: "https://app.disteven.com/"
  },
  {
    id: 2,
    title: "Cipher Bay",
    client: "GrowthTech Startup",
    // category: "Digital Marketing, Content Strategy",
    category: "Web Development, UI/UX Design",
    description:
      "A secure platform for encrypting and decrypting text online.",
    image: "/cipher-bay.PNG",
    demoUrl: "https://cipherbay.vercel.app/home"
  },
  {
    id: 3,
    title: "URL Shortener",
    client: "HealthCare Solutions",
    category: "Web Development, UI/UX Design",
    description:
      "A simple and efficient URL shortener for quick link management.",
    image: "/url-shortner.PNG",
    demoUrl: "https://fexy.vercel.app/"
  },
  {
    id: 4,
    title: "Colors Expo",
    client: "Legacy Financial",
    // category: "Branding, Design",
    category: "Web Application",
    description: "A color palette exploration tool for designers and developers.",
    image: "/colors-expo.PNG",
    demoUrl: "https://find-colors.netlify.app/"
  },
  {
    id: 5,
    title: "Lottery Matching App",
    client: "ProductivityPro",
    category: "Web Development, Product Strategy",
    description: "A random lottery number matcher for testing luck.",
    image: "/lottery.PNG",
    demoUrl: "https://lottery-js.netlify.app/"
  },
  {
    id: 5,
    title: "Collatz Conjecture",
    client: "ProductivityPro",
    category: "Web Development, Product Strategy",
    description: "A visualization of the Collatz Conjecture to explore mathematical patterns.",
    image: "/collatz.PNG",
    demoUrl: "https://collatz-visual.netlify.app/"
  },
  {
    id: 6,
    title: "Pop It",
    client: "Local Business Network",
    // category: "Digital Marketing, SEO",
    category: "Web Application",
    description:
      "A casual popping game for quick, addictive and relaxing gameplay.",
    image: "/pop-game.PNG",
    demoUrl: "https://pop-game.netlify.app/"
  },
  {
    id: 6,
    title: "Quiz It",
    client: "Local Business Network",
    // category: "Digital Marketing, SEO",
    category: "Web Application",
    description:
      "A fun and engaging quiz application for testing knowledge.",
    image: "/quiz-it.PNG",
    demoUrl: "https://quiz-jam.netlify.app/index.html"
  },
  {
    id: 6,
    title: "Les Papilles",
    client: "Local Business Network",
    // category: "Digital Marketing, SEO",
    category: "Web Application",
    description:
      "A visually appealing food, restaurant and online ordering website.",
    image: "/les-papilles.PNG",
    demoUrl: "https://les-papilles.netlify.app/#m"
  },
  {
    id: 6,
    title: "Temperature Plot Chart",
    client: "Local Business Network",
    // category: "Digital Marketing, SEO",
    category: "Web Application",
    description:
      "An interactive temperature plot chart to visualize yearly trends.",
    image: "/temperature-plot-chart.PNG",
    demoUrl: "https://yearly-temperature.netlify.app/"
  },
  {
    id: 6,
    title: "Error Service",
    client: "Local Business Network",
    // category: "Digital Marketing, SEO",
    category: "Web Application",
    description:
      "An application designed to efficiently handle and manage website errors.",
    image: "/error-service.PNG",
    demoUrl: "https://wrng.netlify.app/"
  },
  {
    id: 6,
    title: "To Do List",
    client: "Local Business Network",
    // category: "Digital Marketing, SEO",
    category: "Web Application",
    description:
      "A simple and efficient to-do list web app for task management.",
    image: "/to-do-app.PNG",
    demoUrl: "https://manage-todo.netlify.app/"
  },
  {
    id: 6,
    title: "Big Oven",
    client: "Local Business Network",
    // category: "Digital Marketing, SEO",
    category: "Web Application",
    description:
      "A recipe and meal planning app to explore and manage cooking ideas easily.",
    image: "/big-oven.PNG",
    demoUrl: "https://big-oven.netlify.app/"
  }
]

export default function ProjectsPage() {
  return (
    <PageTransition>
      {/* Hero Section */}
      <section className="container mx-auto relative py-16 md:py-24 container px-4 sm:px-6 lg:px-8">
        <div className="absolute inset-0 from-primary/5 to-background z-0 rounded-lg"></div>
        <div className="relative container z-10">
          <div className="mx-auto max-w-3xl space-y-6 text-center">
            <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl">
              Our <AnimatedGradientText text="Projects" />
            </h1>
            <p className="text-xl text-muted-foreground">Explore our portfolio of successful digital solutions</p>
          </div>
        </div>
      </section>

      {/* Projects Grid */}
      <section className="container mx-auto py-16 md:py-24 container px-4 sm:px-6 lg:px-8">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid gap-8 sm:grid-cols-2 lg:grid-cols-3">
            {projects.map((project) => (
              <Card key={project.id} className="overflow-hidden">
                <div className="aspect-video overflow-hidden">
                  <Image
                    src={project.image || "/placeholder.svg"}
                    width={800}
                    height={600}
                    alt={project.title}
                    loading="lazy"
                    className="h-full w-full object-cover transition-transform duration-300 hover:scale-105"
                  />
                </div>
                <CardContent className="p-6">
                  <div className="space-y-4">
                    <div>
                      <p className="text-sm text-muted-foreground">{project.category}</p>
                      <h3 className="text-xl font-bold">{project.title}</h3>
                      {/* <p className="text-sm text-muted-foreground">Client: {project.client}</p> */}
                    </div>
                    <p className="text-muted-foreground">{project.description}</p>
                    <Link
                      target="_blank"
                      href={`${project.demoUrl}`}
                      className="inline-flex items-center text-sm font-medium text-primary group translate-y-2 transform"
                    >
                      Live Demo <ArrowRight className="ml-1 h-4 w-4" />
                    </Link>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Categories */}
      <section className="container mx-auto bg-muted py-16 md:py-16 container px-4 sm:px-6 lg:px-8">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="mb-12 text-center">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Project Categories</h2>
            <p className="mx-auto mt-4 max-w-[700px] text-muted-foreground">Browse our work by specialty</p>
          </div>
          <div className="grid gap-4 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
            {[
              "Web Development",
              "UI/UX Design",
              "Digital Marketing",
              "E-commerce",
              "Mobile Apps",
              "Branding",
              "SEO",
              "Product Strategy",
            ].map((category, i) => (
              <Card key={i} className="bg-background">
                <CardContent className="flex flex-col items-center p-6 text-center">
                  <h3 className="text-lg font-medium">{category}</h3>
                  <Link
                    href={`/projects/category/${category.toLowerCase().replace(/\s+/g, "-")}`}
                    className="mt-2 inline-flex items-center text-sm font-medium text-primary"
                  >
                    View Projects <ArrowRight className="ml-1 h-4 w-4" />
                  </Link>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="container mx-auto py-16 md:py-24 container px-4 sm:px-6 lg:px-8">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="rounded-lg bg-primary p-8 text-primary-foreground md:p-12">
            <div className="mx-auto max-w-3xl space-y-6 text-center">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
                Ready to start your project?
              </h2>
              <p className="text-primary-foreground/80">
                Let's discuss how we can help your business grow with our comprehensive digital solutions.
              </p>
              <Button size="lg" variant="secondary" asChild>
                <Link href="/contact">Contact Us Today</Link>
              </Button>
            </div>
          </div>
        </div>
      </section>
    </PageTransition>
  )
}
